# Dev
org.gradle.jvmargs=-Xmx2G

# Mod - All field required.
mod.name=CombatLogX Action Bar
mod.id=clx_actionbar
mod.group=combatlogx.expansion.actionbar
mod.version=1.0.0
mod.author=SirBlobman, rcubedev
mod.description=TODO
mod.license=LGPL-3.0
mod.github=https://example.com/todo

# Common subprojects
loader.common=common

# Syntax: loader.sourceset.<sourceset>.dependsOn=comma, separated, list, of, sourceset, dependencies
# Format: <loader>:<sourceset> (loader can be 'common', if loader specific just do 'sourceset')
loader.sourceset.main.dependsOn=common:main
#loader.sourceset.client.dependsOn=common:client
#loader.sourceset.server.dependsOn=common:server

# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
stonecutter_enabled_common_versions=1.21.1, 1.21.10
stonecutter_enabled_fabric_versions=1.21.1, 1.21.10
stonecutter_enabled_forge_versions=
stonecutter_enabled_neoforge_versions=1.21.1, 1.21.10

# The below field are intentionally left blank.
# To edit, please edit gradle.properties for each versions.

# Java
java.version=

# Minecraft
minecraft_version=
min_minecraft_version=

# Mappings
deps.parchment=

# Fabric https://fabricmc.net/versions.html
deps.fabric_loader=
deps.fabric_api=

# Forge
deps.forge=

# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=

# Dependencies
deps.adventure-api
deps.adventure-platform=