# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=21

# Minecraft
minecraft_version=1.21.10
min_minecraft_version=1.21.10

# Mappings
deps.parchment=2025.10.12

# Fabric
deps.fabric_loader=0.17.3
deps.fabric_api=0.138.3

# NeoForge
deps.neoforge=21.10.55-beta

# Dependencies
#deps.toml4j= set in common
#deps.luckperms-api= set in common
deps.adventure-api=4.25.0
deps.adventure-platform=6.7.0
deps.modmenu=16.0.0-rc.1
deps.fabric-permissions-api=0.5.0
deps.placeholder-api=2.8.2+1.21.10