# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=21

# Minecraft
minecraft_version=1.21.1
min_minecraft_version=1.21.1

# Mappings
deps.parchment=2024.11.17

# Fabric
deps.fabric_loader=0.17.3
deps.fabric_api=0.116.1

# NeoForge
deps.neoforge=21.1.216

# Dependencies
#deps.toml4j= set in common
#deps.luckperms-api= set in common
deps.adventure-api=4.17.0
deps.adventure-platform=6.0.1
deps.fabric.adventure-platform=5.14.2
deps.modmenu=11.0.3
deps.fabric-permissions-api=0.3.1
deps.placeholder-api=2.4.2+1.21